// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace FogOfWarPlus
{
    public static partial class FogOfWarLineOfSightShaderKeys
    {
        public static readonly ValueParameterKey<float> Slices = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> VisionCounterBloom = ParameterKeys.NewValue<float>();
    }
}
