// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace FogOfWarPlus
{
    public static partial class FogOfWarLineOfSightShaderKeys
    {
        public static readonly ValueParameterKey<float> Slices = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> VisionRadius = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector3> DetectorPos = ParameterKeys.NewValue<Vector3>();
    }
}
