// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace FogOfWarPlus
{
    public static partial class FogOfWarUnitShaderKeys
    {
        public static readonly ValueParameterKey<bool> IsFogLoaded = ParameterKeys.NewValue<bool>();
        public static readonly ObjectParameterKey<Texture> Fog = ParameterKeys.NewObject<Texture>();
    }
}
