// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace FogOfWarPlus
{
    public static partial class FogOfWarUnitShaderKeys
    {
        public static readonly ValueParameterKey<Vector3> WorldPos = ParameterKeys.NewValue<Vector3>(new Vector3(0,0,0));
        public static readonly ValueParameterKey<Vector3> CameraPos = ParameterKeys.NewValue<Vector3>(new Vector3(0,0,0));
        public static readonly ValueParameterKey<float> CameraRange = ParameterKeys.NewValue<float>(25);
        public static readonly ValueParameterKey<float> DetectDistance = ParameterKeys.NewValue<float>(5);
        public static readonly ValueParameterKey<float> DetectFade = ParameterKeys.NewValue<float>(1);
        public static readonly ValueParameterKey<Vector3> DetectorPos = ParameterKeys.NewValue<Vector3>();
        public static readonly ValueParameterKey<int> MaxDetectors = ParameterKeys.NewValue<int>(100);
    }
}
